#############################################################################
# Makefile for building: /home/dev/src/t_ModeInfo/output/t_ModeInfo.bin
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? ??? 8 00:28:49 2021
# Project:  /home/dev/src/t_ModeInfo/t_ModeInfo.pro
# Template: app
# Command: /usr/bin/qmake-qt48 -config release /home/dev/src/t_ModeInfo/t_ModeInfo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DNDEBUG -D__RHEL__ -D__RHEL_MAJOR__=7 -D__RHEL_MINOR__=4
CFLAGS        = -m64 -pipe -Wall -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -O2 -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -Wall -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -O2 -std=gnu++98 -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/lib64/qt48/mkspecs/default -I/home/dev/src/t_ModeInfo -I/home/dev/src/t_ModeInfo/tmp/t_ModeInfo.bin/release/moc
LINK          = g++
LFLAGS        = -m64 -Wl,-z,relro -Wl,--as-needed -Wl,-O1 -Wl,-rpath-link,/home/dev/src/t_ModeInfo/output
LIBS          = $(SUBLIBS)  -L/home/dev/src/t_ModeInfo/output -ldl -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt48
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = tmp/release/

####### Files

SOURCES       = main.cpp 
OBJECTS       = tmp/release/main.o
DIST          = /usr/lib64/qt48/mkspecs/common/unix.conf \
		/usr/lib64/qt48/mkspecs/common/linux.conf \
		/usr/lib64/qt48/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt48/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt48/mkspecs/common/g++-base.conf \
		/usr/lib64/qt48/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt48/mkspecs/qconfig.pri \
		/usr/lib64/qt48/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib64/qt48/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt48/mkspecs/features/qt_config.prf \
		/usr/lib64/qt48/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt48/mkspecs/features/default_pre.prf \
		/nitasoft.cache/share/features/include/pre/functions.pri \
		/nitasoft.cache/share/features/include/pre/config.pri \
		/soft/share/features/default_pre.prf \
		/usr/lib64/qt48/mkspecs/features/release.prf \
		/usr/lib64/qt48/mkspecs/features/default_post.prf \
		/nitasoft.cache/share/features/include/post/target_check.pri \
		/nitasoft.cache/share/features/include/post/check_files_exists.pri \
		/nitasoft.cache/share/features/include/post/config.pri \
		/nitasoft.cache/share/features/include/post/std.pri \
		/nitasoft.cache/share/features/include/post/nita_defaults.pri \
		/nitasoft.cache/share/features/include/post/install.pri \
		/nitasoft.cache/share/features/include/post/translations.pri \
		/nitasoft.cache/share/features/include/post/phony_target.pri \
		/nitasoft.cache/share/features/include/post/optflags.pri \
		/nitasoft.cache/share/features/include/post/unix/abicheck.pri \
		/soft/share/features/default_post.prf \
		/soft/share/features/nls.prf \
		/usr/lib64/qt48/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt48/mkspecs/features/warn_on.prf \
		/usr/lib64/qt48/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt48/mkspecs/features/moc.prf \
		/usr/lib64/qt48/mkspecs/features/shared.prf \
		/usr/lib64/qt48/mkspecs/features/resources.prf \
		/usr/lib64/qt48/mkspecs/features/uic.prf \
		/nitasoft.cache/share/features/include/finality/filters.pri \
		/nitasoft.cache/share/features/include/finality/install_to_destdir.pri \
		/nitasoft.cache/share/features/include/finality/check_target.pri \
		/soft/share/features/finality.prf \
		/home/dev/src/t_ModeInfo/t_ModeInfo.pro
QMAKE_TARGET  = t_ModeInfo.bin
DESTDIR       = /home/dev/src/t_ModeInfo/output/
TARGET        = /home/dev/src/t_ModeInfo/output/t_ModeInfo.bin

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: /home/dev/src/t_ModeInfo/Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) /home/dev/src/t_ModeInfo/output/ || $(MKDIR) /home/dev/src/t_ModeInfo/output/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

/home/dev/src/t_ModeInfo/Makefile: /home/dev/src/t_ModeInfo/t_ModeInfo.pro  /usr/lib64/qt48/mkspecs/default/qmake.conf /usr/lib64/qt48/mkspecs/common/unix.conf \
		/usr/lib64/qt48/mkspecs/common/linux.conf \
		/usr/lib64/qt48/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt48/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt48/mkspecs/common/g++-base.conf \
		/usr/lib64/qt48/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt48/mkspecs/qconfig.pri \
		/usr/lib64/qt48/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib64/qt48/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt48/mkspecs/features/qt_config.prf \
		/usr/lib64/qt48/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt48/mkspecs/features/default_pre.prf \
		/nitasoft.cache/share/features/include/pre/functions.pri \
		/nitasoft.cache/share/features/include/pre/config.pri \
		/soft/share/features/default_pre.prf \
		/usr/lib64/qt48/mkspecs/features/release.prf \
		/usr/lib64/qt48/mkspecs/features/default_post.prf \
		/nitasoft.cache/share/features/include/post/target_check.pri \
		/nitasoft.cache/share/features/include/post/check_files_exists.pri \
		/nitasoft.cache/share/features/include/post/config.pri \
		/nitasoft.cache/share/features/include/post/std.pri \
		/nitasoft.cache/share/features/include/post/nita_defaults.pri \
		/nitasoft.cache/share/features/include/post/install.pri \
		/nitasoft.cache/share/features/include/post/translations.pri \
		/nitasoft.cache/share/features/include/post/phony_target.pri \
		/nitasoft.cache/share/features/include/post/optflags.pri \
		/nitasoft.cache/share/features/include/post/unix/abicheck.pri \
		/soft/share/features/default_post.prf \
		/soft/share/features/nls.prf \
		/usr/lib64/qt48/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt48/mkspecs/features/warn_on.prf \
		/usr/lib64/qt48/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt48/mkspecs/features/moc.prf \
		/usr/lib64/qt48/mkspecs/features/shared.prf \
		/usr/lib64/qt48/mkspecs/features/resources.prf \
		/usr/lib64/qt48/mkspecs/features/uic.prf \
		/nitasoft.cache/share/features/include/finality/filters.pri \
		/nitasoft.cache/share/features/include/finality/install_to_destdir.pri \
		/nitasoft.cache/share/features/include/finality/check_target.pri \
		/soft/share/features/finality.prf
	$(QMAKE) -config release /home/dev/src/t_ModeInfo/t_ModeInfo.pro
/usr/lib64/qt48/mkspecs/common/unix.conf:
/usr/lib64/qt48/mkspecs/common/linux.conf:
/usr/lib64/qt48/mkspecs/common/gcc-base.conf:
/usr/lib64/qt48/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt48/mkspecs/common/g++-base.conf:
/usr/lib64/qt48/mkspecs/common/g++-unix.conf:
/usr/lib64/qt48/mkspecs/qconfig.pri:
/usr/lib64/qt48/mkspecs/modules/qt_webkit_version.pri:
/usr/lib64/qt48/mkspecs/features/qt_functions.prf:
/usr/lib64/qt48/mkspecs/features/qt_config.prf:
/usr/lib64/qt48/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt48/mkspecs/features/default_pre.prf:
/nitasoft.cache/share/features/include/pre/functions.pri:
/nitasoft.cache/share/features/include/pre/config.pri:
/soft/share/features/default_pre.prf:
/usr/lib64/qt48/mkspecs/features/release.prf:
/usr/lib64/qt48/mkspecs/features/default_post.prf:
/nitasoft.cache/share/features/include/post/target_check.pri:
/nitasoft.cache/share/features/include/post/check_files_exists.pri:
/nitasoft.cache/share/features/include/post/config.pri:
/nitasoft.cache/share/features/include/post/std.pri:
/nitasoft.cache/share/features/include/post/nita_defaults.pri:
/nitasoft.cache/share/features/include/post/install.pri:
/nitasoft.cache/share/features/include/post/translations.pri:
/nitasoft.cache/share/features/include/post/phony_target.pri:
/nitasoft.cache/share/features/include/post/optflags.pri:
/nitasoft.cache/share/features/include/post/unix/abicheck.pri:
/soft/share/features/default_post.prf:
/soft/share/features/nls.prf:
/usr/lib64/qt48/mkspecs/features/unix/thread.prf:
/usr/lib64/qt48/mkspecs/features/warn_on.prf:
/usr/lib64/qt48/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt48/mkspecs/features/moc.prf:
/usr/lib64/qt48/mkspecs/features/shared.prf:
/usr/lib64/qt48/mkspecs/features/resources.prf:
/usr/lib64/qt48/mkspecs/features/uic.prf:
/nitasoft.cache/share/features/include/finality/filters.pri:
/nitasoft.cache/share/features/include/finality/install_to_destdir.pri:
/nitasoft.cache/share/features/include/finality/check_target.pri:
/soft/share/features/finality.prf:
qmake:  FORCE
	@$(QMAKE) -config release /home/dev/src/t_ModeInfo/t_ModeInfo.pro

dist: 
	@$(CHK_DIR_EXISTS) tmp/release/t_ModeInfo.bin1.0.0 || $(MKDIR) tmp/release/t_ModeInfo.bin1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) tmp/release/t_ModeInfo.bin1.0.0/ && $(COPY_FILE) --parents main.cpp tmp/release/t_ModeInfo.bin1.0.0/ && (cd `dirname tmp/release/t_ModeInfo.bin1.0.0` && $(TAR) t_ModeInfo.bin1.0.0.tar t_ModeInfo.bin1.0.0 && $(COMPRESS) t_ModeInfo.bin1.0.0.tar) && $(MOVE) `dirname tmp/release/t_ModeInfo.bin1.0.0`/t_ModeInfo.bin1.0.0.tar.gz . && $(DEL_FILE) -r tmp/release/t_ModeInfo.bin1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) /home/dev/src/t_ModeInfo/Makefile


check: first

nls:

po:

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: /home/dev/src/t_ModeInfo/tmp/t_ModeInfo.bin/release/ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) /home/dev/src/t_ModeInfo/tmp/t_ModeInfo.bin/release/ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_clean: 

####### Compile

tmp/release/main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/release/main.o main.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/dev/soft/bin/ || $(MKDIR) $(INSTALL_ROOT)/home/dev/soft/bin/ 
	-$(INSTALL_PROGRAM) "/home/dev/src/t_ModeInfo/output/$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home/dev/soft/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/home/dev/soft/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/dev/soft/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/dev/soft/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

